# Generated by Django 3.2.19 on 2023-09-15 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('mailid', models.EmailField(max_length=254)),
                ('subject', models.TextField(max_length=500)),
                ('degree', models.FileField(upload_to='')),
            ],
        ),
    ]
