# Generated by Django 3.2.19 on 2023-09-15 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appss', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='degree',
            field=models.FileField(upload_to='teacher_degrees/'),
        ),
    ]
