# Generated by Django 3.2.19 on 2023-09-15 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appss', '0003_teacher_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='teacherlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=10000)),
                ('url', models.CharField(max_length=100)),
            ],
        ),
    ]
